In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
data = pd.read_csv('binary.csv')

In [49]:
data.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

### Data Preprocessing

In [50]:
df = pd.concat([data, pd.get_dummies(data['rank'], prefix='rank')],axis=1)
df = df.drop('rank',axis=1)
df.head()

   admit  gre   gpa  rank_1  rank_2  rank_3  rank_4
0      0  380  3.61       0       0       1       0
1      1  660  3.67       0       0       1       0
2      1  800  4.00       1       0       0       0
3      1  640  3.19       0       0       0       1
4      0  520  2.93       0       0       0       1

In [51]:
for field in ['gre', 'gpa']:
    mean, std = df[field].mean(), df[field].std()
    df.loc[:,field] = (df[field]-mean)/std

In [52]:
df.head()

   admit       gre       gpa  rank_1  rank_2  rank_3  rank_4
0      0 -1.798011  0.578348       0       0       1       0
1      1  0.625884  0.736008       0       0       1       0
2      1  1.837832  1.603135       1       0       0       0
3      1  0.452749 -0.525269       0       0       0       1
4      0 -0.586063 -1.208461       0       0       0       1

In [53]:
sample = np.random.choice(df.index, size=int(len(data)*0.9), replace=False)
data, test_data = df.ix[sample], df.drop(sample)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [54]:
x_train, y_train = data.drop('admit',axis=1), data['admit']
x_test, y_test = test_data.drop('admit', axis=1), test_data['admit']

In [58]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

weights = np.random.normal(scale=1 / x_train.shape[1]**.5, size=x_train.shape[1])
learning_rate = 0.1
epochs = 10000
last_loss = None
c=0
for e in range(epochs):
    del_w = np.zeros(len(weights))
    for x, y in zip(x_train.values, y_train.values):
        a = sigmoid(np.dot(x, weights))
        error = y - a
        
        error_term = error * a * (1 - a)
        
        del_w += error_term * x
    weights += learning_rate*error_term/x_train.shape[0]
    
    if e%100 == 0:
        out = sigmoid(np.dot(x_train,weights))
        loss = np.mean((out-y_train)**2)
        if last_loss and last_loss<loss:
            print("WARNING - Loss Increasing..")
            print("Train Loss: {}".format(loss))
            c+=1
            if c==3:
                break
        else:
            print("Loss Decreasing..")
            print("Train Loss: {}".format(loss))
        last_loss = loss

Loss Decreasing..
Train Loss: 0.23108135539433713
Loss Decreasing..
Train Loss: 0.23101993253989322
Loss Decreasing..
Train Loss: 0.23095848213853845
Loss Decreasing..
Train Loss: 0.23089700438771596
Loss Decreasing..
Train Loss: 0.2308354994867501
Loss Decreasing..
Train Loss: 0.23077396763685817
Loss Decreasing..
Train Loss: 0.23071240904116735
Loss Decreasing..
Train Loss: 0.23065082390472658
Loss Decreasing..
Train Loss: 0.23058921243452113
Loss Decreasing..
Train Loss: 0.23052757483948585
Loss Decreasing..
Train Loss: 0.23046591133052216
Loss Decreasing..
Train Loss: 0.23040422212050815
Loss Decreasing..
Train Loss: 0.23034250742431744
Loss Decreasing..
Train Loss: 0.23028076745882944
Loss Decreasing..
Train Loss: 0.2302190024429475
Loss Decreasing..
Train Loss: 0.23015721259761165
Loss Decreasing..
Train Loss: 0.23009539814581417
Loss Decreasing..
Train Loss: 0.2300335593126136
Loss Decreasing..
Train Loss: 0.2299716963251506
Loss Decreasing..
Train Loss: 0.22990980941266342
Loss Decreasing..
Train Loss: 0.2298478988065021
Loss Decreasing..
Train Loss: 0.22978596474014393
Loss Decreasing..
Train Loss: 0.22972400744920898
Loss Decreasing..
Train Loss: 0.22966202717147766
Loss Decreasing..
Train Loss: 0.2296000241469013
Loss Decreasing..
Train Loss: 0.22953799861762378
Loss Decreasing..
Train Loss: 0.229475950827993
Loss Decreasing..
Train Loss: 0.2294138810245791
Loss Decreasing..
Train Loss: 0.2293517894561901
Loss Decreasing..
Train Loss: 0.22928967637388703
Loss Decreasing..
Train Loss: 0.22922754203100165
Loss Decreasing..
Train Loss: 0.22916538668315165
Loss Decreasing..
Train Loss: 0.22910321058825814
Loss Decreasing..
Train Loss: 0.22904101400656107
Loss Decreasing..
Train Loss: 0.22897879720063752
Loss Decreasing..
Train Loss: 0.22891656043541606
Loss Decreasing..
Train Loss: 0.228854303978197
Loss Decreasing..
Train Loss: 0.2287920280986664
Loss Decreasing..
Train Loss: 0.22872973306891484
Loss Decreasing..
Train Loss: 0.22866741916345454
Loss Decreasing..
Train Loss: 0.2286050866592356
Loss Decreasing..
Train Loss: 0.22854273583566556
Loss Decreasing..
Train Loss: 0.228480366974625
Loss Decreasing..
Train Loss: 0.22841798036048647
Loss Decreasing..
Train Loss: 0.2283555762801317
Loss Decreasing..
Train Loss: 0.22829315502297007
Loss Decreasing..
Train Loss: 0.22823071688095634
Loss Decreasing..
Train Loss: 0.22816826214860864
Loss Decreasing..
Train Loss: 0.22810579112302826
Loss Decreasing..
Train Loss: 0.22804330410391607
Loss Decreasing..
Train Loss: 0.22798080139359095
Loss Decreasing..
Train Loss: 0.22791828329701191
Loss Decreasing..
Train Loss: 0.22785575012179196
Loss Decreasing..
Train Loss: 0.22779320217822144
Loss Decreasing..
Train Loss: 0.22773063977928412
Loss Decreasing..
Train Loss: 0.22766806324067784
Loss Decreasing..
Train Loss: 0.227605472880833
Loss Decreasing..
Train Loss: 0.22754286902093296
Loss Decreasing..
Train Loss: 0.22748025198493257
Loss Decreasing..
Train Loss: 0.22741762209957833
Loss Decreasing..
Train Loss: 0.22735497969442856
Loss Decreasing..
Train Loss: 0.22729232510187225
Loss Decreasing..
Train Loss: 0.22722965865715056
Loss Decreasing..
Train Loss: 0.22716698069837607
Loss Decreasing..
Train Loss: 0.22710429156655268
Loss Decreasing..
Train Loss: 0.2270415916055981
Loss Decreasing..
Train Loss: 0.2269788811623611
Loss Decreasing..
Train Loss: 0.22691616058664554
Loss Decreasing..
Train Loss: 0.22685343023123
Loss Decreasing..
Train Loss: 0.2267906904518876
Loss Decreasing..
Train Loss: 0.2267279416074088
Loss Decreasing..
Train Loss: 0.22666518405962208
Loss Decreasing..
Train Loss: 0.22660241817341506
Loss Decreasing..
Train Loss: 0.22653964431675563
Loss Decreasing..
Train Loss: 0.22647686286071536
Loss Decreasing..
Train Loss: 0.22641407417948944
Loss Decreasing..
Train Loss: 0.2263512786504194
Loss Decreasing..
Train Loss: 0.2262884766540154
Loss Decreasing..
Train Loss: 0.22622566857397783
Loss Decreasing..
Train Loss: 0.22616285479721945
Loss Decreasing..
Train Loss: 0.2261000357138906
Loss Decreasing..
Train Loss: 0.22603721171739682
Loss Decreasing..
Train Loss: 0.22597438320442675
Loss Decreasing..
Train Loss: 0.2259115505749721
Loss Decreasing..
Train Loss: 0.225848714232351
Loss Decreasing..
Train Loss: 0.2257858745832326
Loss Decreasing..
Train Loss: 0.22572303203765845
Loss Decreasing..
Train Loss: 0.22566018700906734
Loss Decreasing..
Train Loss: 0.2255973399143197
Loss Decreasing..
Train Loss: 0.22553449117371932
Loss Decreasing..
Train Loss: 0.22547164121103844
Loss Decreasing..
Train Loss: 0.22540879045354215
Loss Decreasing..
Train Loss: 0.2253459393320121
Loss Decreasing..
Train Loss: 0.22528308828077093
Loss Decreasing..
Train Loss: 0.22522023773770733
Loss Decreasing..
Train Loss: 0.22515738814429942
Loss Decreasing..
Train Loss: 0.22509453994564207
Loss Decreasing..
Train Loss: 0.2250316935904685
Loss Decreasing..
Train Loss: 0.22496884953117907
Loss Decreasing..
Train Loss: 0.22490600822386383

In [60]:
pred = sigmoid(np.dot(x_test,weights))

In [62]:
pred = pred>0.5

In [64]:
accuracy = np.mean(pred==y_test)

In [67]:
print("Accuracy of the model is: ",accuracy*100)

Accuracy of the model is:  52.5